import web3 from './web3';

// contract address
const address = '0xc1dDFC4d39038D94BA3F365485e0cE8168274a51';
const abi = [ { constant: true,
    inputs: [],
    name: 'manager',
    outputs: [ [Object] ],
    payable: false,
    stateMutability: 'view',
    type: 'function' },
  { constant: true,
    inputs: [],
    name: 'getPlayers',
    outputs: [ [Object] ],
    payable: false,
    stateMutability: 'view',
    type: 'function' },
  { constant: false,
    inputs: [],
    name: 'getWinner',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function' },
  { constant: false,
    inputs: [],
    name: 'play',
    outputs: [],
    payable: true,
    stateMutability: 'payable',
    type: 'function' },
  { constant: true,
    inputs: [],
    name: 'getManager',
    outputs: [ [Object] ],
    payable: false,
    stateMutability: 'view',
    type: 'function' },
  { constant: true,
    inputs: [ [Object] ],
    name: 'players',
    outputs: [ [Object] ],
    payable: false,
    stateMutability: 'view',
    type: 'function' },
  { inputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'constructor' } ];
export default new web3.eth.Contract(abi, address);
